In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('https://github.com/codebasics/py/raw/master/ML/4_save_model/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

array([859554.79452055])

In [9]:
import pickle   # it allows you to searilize you python object into a file
with open ('model_pickle','wb') as f:          # here we open a file and In wb w means write mode b means bineary of files
    pickle.dump(model,f)
    
# when we run this what actually happens is in my working directory it created model_pickle

In [10]:
with open ('model_pickle','rb') as f:    # here In rb r means read mode and b means its a binary of file so we put b there
    mp=pickle.load(f)   # now I have my model loaded from a file into a memory and mp is the object

In [12]:
mp.predict([[5000]])  # now it will give me the same answer

array([859554.79452055])

In [ ]:
# there is second approach of saving model to a file which is using sklearn joblib
# as per the documentation if your model consist of large numpy arrays then using joblib might be more efficient 

In [15]:
# Save Trained Model Using joblib
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\MyPC\anaconda3\lib\site-packages\sklearn\externals\__init__.py)

In [16]:
joblib.dump(model, 'model_joblib')

NameError: name 'joblib' is not defined

In [ ]:
# Load Saved Model
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

In [ ]:
mj.intercept_

In [ ]:
mj.predict([[5000]])